### ISSUE TITLE
Not rendering special characters correctly (æøå)

### ISSUE THREAD

**Issue by NoLooseEnds** [Wellenline/waveline-web#1]
<img width="398" alt="Screenshot 2020-04-15 at 22 14 49" src="https://user-images.githubusercontent.com/4103531/79384120-9ddb2d00-7f66-11ea-8a60-5f9bdc555764.png">

**Comment by MihkelBaranov** [comment]
Weird, I'm using Open Sans from google fonts and unless you've blocked Google it should render Latin characters just fine

![Screen Shot 2020-04-16 at 8 08 27 PM](https://user-images.githubusercontent.com/3790782/79485539-0e915080-801e-11ea-8075-468e30c9291a.png)


https://fonts.google.com/specimen/Open+Sans

> This version contains the complete 897 character set, which includes the standard **ISO Latin 1, Latin CE, Greek and Cyrillic** character sets. Open Sans was designed with an upright stress, open forms and a neutral, yet friendly appearance. It was optimized for print, web, and mobile interfaces, and has excellent legibility characteristics in its letterforms.

**Comment by NoLooseEnds** [comment]
I tested with Firefox, but I don't think that should matter. It could be an error with the files meta data. I'll check some more and get back to you.

**Comment by NoLooseEnds** [comment]
And you can close this. I jumped the gun, sorry! The error was with the meta data in the file itself.
